apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-frontend
  template:
    metadata:
      labels:
        app: hackathon-frontend
    spec:
      containers:
        - name: hackathon-frontend
          image: ECR_REPO_URL_PLACEHOLDER:frontend-latest
          imagePullPolicy: Always 
          ports:
            - containerPort: 8501
          resources:
            requests:
              cpu: "250m"      
              memory: "256Mi"
            limits:
              cpu: "500m"      
              memory: "512Mi"
          envFrom:
            - secretRef:
                name: hackathon-frontend-secrets