apiVersion: v1
kind: Service
metadata:
  name: hackathon-frontend-lb
spec:
  type: LoadBalancer
  selector:
    app: hackathon-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501